apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-deployment
  labels:
    app: gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: python-app
        image: "europe-west1-docker.pkg.dev/yuyatinnefeld-dev/docker-repo/python-app:1.0.0"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gcp-golang-service
  namespace: gcp-deployment-dev
  labels:   
    app.kubernetes.io/managed-by: "gcp-cloud-build-deployment"
spec:
  selector:
    app: gcp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      name: http-gcp
  type: LoadBalancer